/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_help.h"
/* Header for class pers_zhc_tools_utils_S */

#ifndef _Included_pers_zhc_tools_utils_S
#define _Included_pers_zhc_tools_utils_S
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_zhc_tools_utils_S
 * Method:    ex1
 * Signature: (Ljava/util/jar/JarInputStream;)V
 */
JNIEXPORT void JNICALL Java_pers_zhc_tools_utils_ExternalJNI_ex1
        (JNIEnv *env, jobject activity);

#ifdef __cplusplus
}
#endif
#endif